services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: muchtodo-api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://mongodb:27017
      - DB_NAME=muchtodo
      - JWT_SECRET_KEY=supersecretkey
      - JWT_EXPIRATION_HOURS=72
      - ENABLE_CACHE=false
      - LOG_LEVEL=info
      - LOG_FORMAT=json

volumes:
  mongo_data:
